global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "pet-project"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:9100"]
